sudo: true
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  firefox: "66.0"
  chrome: stable

before_script:
  - npm install -g polymer-cli web-component-tester

script:
  - wct --npm --env saucelabs
